### ISSUE TITLE
Module file reference

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel-Gallery#11]
https://github.com/statnet/EpiModel-Gallery/blob/adc23562874168eae179d5a955c51069fc96f027/2018-10-SEIRwithAllOrNothingVaccination/model.R#L87

@connor-vanmeter this will not pass on Travis CI because of the local reference to the `module-fx.R` file.

this needs to just be:

```r
source("module-fx.R", echo = TRUE)
```

You can change the local working directory with `setwd`, use the drop down menu (session -> set working directory -> source file location), or use an Rstudio Project file.

**Comment by connor-vanmeter** [comment]
Set working directory and used suggested `source("module-fx.R", echo = TRUE)` in the All Or Nothing Vaccine Model to source from the module-fx.R file. Closing issue.
