### ISSUE TITLE
Basic syphilis model 

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel-Gallery#13]
This model would include the natural history of syphilis (an extension SEIRS) in a MSM population, with the first iteration not including testing and treatment, and perhaps a second iteration doing so.

**Comment by smjenness** [comment]
Might be useful to draw on the SEIR/SEIRS model examples here:
https://github.com/statnet/EpiModel-Gallery/tree/master/2018-08-AddingAnExposedState

**Comment by kweiss2** [comment]
@saintmiracle06 
- [ ] Build simple progression and transmission model
- [ ] Adjustments to transmission and progression (epi tracker for length of time in stages before progression)
- [ ] Build stage-specific symptoms (one-time assignment or cumulative over a stage?)
- [ ] Build treatment process (symptoms-based)
- [ ] Build testing/screening process (for asymptomatic individuals)

**Comment by saintmiracle06** [comment]
Qs:
1. Stage-specific symptoms, can symptomatic patients transfer back to non-symptomatic without treatment?
2. Different prob of transition to symptomatic at each step?

**Comment by kweiss2** [comment]
Per what we were talking about yesterday, this was one of the options (fixed assignment of symptoms at time of stage transition vs. cumulative development of symptoms).

1. We had been assuming stages were independent (e.g. can be symptomatic in primary but asymptomatic in secondary).
2. Yes, determined by stage length and by probability of symptoms in that stage. For argument's sake, would we also want to allow for transition (within a single stage) from no symptoms --> symptoms --> no symptoms? Probably not for simplicity's sake?
