### ISSUE TITLE
Vaccination model

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel-Gallery#4]
Could follow two examples of all-or-nothing and leaky vaccine

**Comment by connor-vanmeter** [comment]
Leaky vs all-or-nothing vaccine:
[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3798059/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3798059/)
[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3798059/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4394665/)
[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3798059/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2657090/)

**Comment by venkataduvvuri** [comment]
Thank you for the articles.

I am reading one of the articles "Distinguishing vaccine efficacy and effectiveness". I will try to write code for this.

**Comment by connor-vanmeter** [comment]
Updates:

[In the Module]
1. Changed is.na to is.null for determining missing numeric variables
2. Rearranged timing of missing vaccination and/or protection rate "stop" error message to precede automatic error message from R
3. Resolved some issues with attribute vector lengths

[In the Model]
1. Removed plots that were unused but were causing failures in Travis.
2. Updated plots (removed `y=` and added `type="epi"`)

--To-do
1. Continue to validate.
2. Understand difference between sum of s, e, i, r, v individuals and network size
